---
- name: Required variables defined
  assert:
    that:
      - podluck_container_name is defined
      - podluck_container_dependencies is defined

- name: Podluck container systemd override directory present
  tags:
    - configuration
  file:
    state: directory
    path: "{{ podluck_systemd_config_dir }}/{{ podluck_pod_name }}@{{ podluck_container_name }}.service.d"
    owner: "{{ podluck_systemd_override_dir_owner | default(omit) }}"
    group: "{{ podluck_systemd_override_dir_group | default(omit) }}"
    mode: "{{ podluck_systemd_override_dir_mode }}"

- name: Podluck container dependency present
  loop: "{{ podluck_container_dependencies }}"
  loop_control:
    loop_var: podluck_container_bind_name
  copy:
    content: |
      [Unit]
      BindsTo={{ podluck_pod_name }}@{{ podluck_container_bind_name }}.service
      After={{ podluck_pod_name }}@{{ podluck_container_bind_name }}.service
    dest: "{{ podluck_systemd_config_dir }}/{{ podluck_pod_name }}@{{ podluck_container_name }}.service.d/bind-to-{{ podluck_container_bind_name }}.conf"
    owner: "{{ podluck_systemd_override_file_owner | default(omit) }}"
    group: "{{ podluck_systemd_override_file_group | default(omit) }}"
    mode: "{{ podluck_systemd_override_file_mode }}"
