---
- name: Required variables defined
  assert:
    that:
      - podluck_pod_dependency is defined
      - podluck_pod_dependency.container is defined
      - podluck_pod_dependency.wants is defined

- name: Podluck container dependency absent
  file:
    path: "{{ podluck_systemd_config_dir }}/{{ podluck_pod_name }}@{{ podluck_pod_dependency.container }}.service.d/wants-{{ podluck_pod_dependency.wants }}.conf"
    state: absent
