---
- name: Required variables defined
  assert:
    that:
      - podluck_pod_dependency is defined
      - podluck_pod_dependency.container is defined
      - podluck_pod_dependency.wants is defined

- name: Podluck container systemd override directory present
  tags:
    - configuration
  file:
    state: directory
    path: "{{ podluck_systemd_config_dir }}/{{ podluck_pod_name }}@{{ podluck_pod_dependency.container }}.service.d"
    owner: "{{ podluck_systemd_override_dir_owner | default(omit) }}"
    group: "{{ podluck_systemd_override_dir_group | default(omit) }}"
    mode: "{{ podluck_systemd_override_dir_mode }}"

- name: Podluck container dependency present
  copy:
    content: |
      [Unit]
      Wants={{ podluck_pod_name }}@{{ podluck_pod_dependency.wants }}.service
      After={{ podluck_pod_name }}@{{ podluck_pod_dependency.wants }}.service
      PartOf={{ podluck_pod_name }}@{{ podluck_pod_dependency.wants }}.service
    dest: "{{ podluck_systemd_config_dir }}/{{ podluck_pod_name }}@{{ podluck_pod_dependency.container }}.service.d/wants-{{ podluck_pod_dependency.wants }}.conf"
    owner: "{{ podluck_systemd_override_file_owner | default(omit) }}"
    group: "{{ podluck_systemd_override_file_group | default(omit) }}"
    mode: "{{ podluck_systemd_override_file_mode }}"
