---
- name: Required variables defined
  assert:
    that:
      - podluck_pod_name is defined
      - podluck_pod_containers is defined
      - podluck_systemd_scope is defined

- name: Systemd pod unit disabled
  systemd:
    name: "{{ podluck_pod_name }}.service"
    scope: "{{ podluck_systemd_scope }}"
    enabled: false

- name: Systemd container unit enabled/disabled
  when: podluck_pod_enabled is defined
  loop: "{{ podluck_pod_containers }}"
  loop_control:
    loop_var: podluck_container_name
  systemd:
    name: "{{ podluck_pod_name }}@{{ podluck_container_name }}.service"
    scope: "{{ podluck_systemd_scope }}"
    enabled: false

- name: Podluck systemd unit files absent
  register: podluck_pod_systemd_unit_result
  loop_control:
    loop_var: podluck_unit_name
  loop:
      - "{{ podluck_pod_name }}.service"
      - "{{ podluck_pod_name }}@.service"
      - "{{ podluck_pod_name }}.target"
  file:
    path: "{{ podluck_systemd_unit_dir }}/{{ podluck_unit_name }}"
    state: absent

- name: Podluck pod dependency absent
  register: podluck_pod_dependencies_result
  with_dict: "{{ podluck_pod_dependencies }}"
  loop_control:
    loop_var: podluck_pod_dependency_entry
  vars:
    podluck_container_name: "{{ podluck_pod_dependency_entry.key }}"
    podluck_container_dependencies: "{{ podluck_pod_dependency_entry.value | list }}"
  include_tasks: dependencies_absent.yml

- name: Systemd daemon reloaded
  when: >-
    podluck_pod_systemd_unit_result is changed
    or podluck_pod_dependencies_result is changed
  systemd:
    scope: "{{ podluck_systemd_scope }}"
    daemon_reload: true
